// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

float Scale;
int2 BoidPosition;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    Result[id.xy] = float4(abs(BoidPosition.x - id.x),abs(BoidPosition.y - id.y),0.0,0.0);
    Result[id.xy] = Result[id.xy] * Scale;
}
