// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

Texture2D<float> DistanceData;
Texture2D<float4> ColorLookup;
int ColorLookupSize;

RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    Result[id.xy] = ColorLookup[int2((int)(DistanceData[id.xy]*(float)ColorLookupSize),0)];
}
